# MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/feedback_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Rohith@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf settings (Optional)
spring.thymeleaf.cache=false
spring.application.name=feedback-system

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Enable detailed logging for debugging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.com.feedback.feedback.system=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
spring.mvc.throw-exception-if-no-handler-found=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.enabled=true

logging.level.org.springframework=DEBUG
logging.level.root=DEBUG

